// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDENbm_u0RDTDdu0NUeJEUhx8j4UQDPNww',
    appId: '1:683453713493:web:b44d192335456633a818dc',
    messagingSenderId: '683453713493',
    projectId: 'ultimaapps1',
    authDomain: 'ultimaapps1.firebaseapp.com',
    storageBucket: 'ultimaapps1.firebasestorage.app',
    measurementId: 'G-X8PMSSM9MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ0WRn5y8W-vDRKWmAcX7oTYzcVislVCc',
    appId: '1:683453713493:android:1f4d73e712df164ea818dc',
    messagingSenderId: '683453713493',
    projectId: 'ultimaapps1',
    storageBucket: 'ultimaapps1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SJPouCoNdgsuAGi20-xVZ0wT3ldoDcg',
    appId: '1:683453713493:ios:bb59445094e431a8a818dc',
    messagingSenderId: '683453713493',
    projectId: 'ultimaapps1',
    storageBucket: 'ultimaapps1.firebasestorage.app',
    iosBundleId: 'com.example.appWebV1',
  );
}
